name = "cbreed-author-dashboard"
compatibility_date = "2025-07-08"

[build]
command = ""
cwd = "public"

[[d1_databases]]
binding = "DB"
database_name = "book-shelf"
database_id = "f0159cd3-fe12-4178-95f2-5b77165b93e8"

[placement]
mode = "smart"
